### ISSUE TITLE
[Steamless] File missing expected '.bind' section!

### ISSUE THREAD

**Issue by BiOSF2** [Cracko298/UE4-AES-Key-Extracting-Guide#4] opened 2023-08-04 05:26 UTC
I was following this guide to try and datamine PAYDAY 3's closed beta while it's out. I got as far as using Steamless to remove the DRM, but it seems to not be working. I tried leading it to the Shipping.exe file and the Win64 folder, but neither worked. Directing it to the folder spat out a basic 'file not found' type error, and directing it to the Shipping.exe file spat [this](https://imgur.com/zhYKdJq) out in the log. The location of the exe looks like [this](https://imgur.com/odWij4I) by the way.

**Comment by Cracko298** [comment] 2023-08-04 11:21
Hello, thanks for creating an issue.
This means that the SteamDRM is not in place. Thus means you can continue with the AES 256 Key Mining as normal. But just without this step. So you can search for your keys without needing to remove any DRM.

If you're still experiencing issues after this response, I would reccomened researching how to use the gold leaf emulator. Or asking around in the UE4 Modding Community if your issue is still unresolved.

Note: Payday 3 is a newer game, which might means it might prevent kwy extraction or have its own custom DRM that we as modders are unsure about.

**Comment by Cracko298** [comment] 2023-08-08 11:19
Closing the issue as the Original Poster is not responding.
Assuming the problem is fixed, will allow reopening if applicable.

**Closed by Cracko298** 2023-08-08 11:19 UTC
